var map1 = `
      WiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWi
      WiWiW W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W Wi
      WiWiW D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi                             
      WiWiW D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi                           
      WiWiW D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi                            
      WiWiW D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi
      WiWiW D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi
      WiWiW W W W W W W W W W W W W W W W W W W W W W W W W W W W D D D D D D D D D D D D D W W W W W W W W W W W W W W W W W W W W W W W W D D D D D D D D D D D D D D D D D D D D D D W Wi
      WiWiW                   W           W           W         W D D D D D D D D D D D D D W                     W                       W D D D D D D D D D D D D D D D D D D D D D D W Wi
      WiWiW                   W           W           W         W D D D D D D D D D D D D D W                                             W W W W W W W D D D D D D D D D D D D D D D D W Wi
      WiWiW                   W           W           W         W D D D D D D D D D D D D D W                     W                       W           W D D D D D D D D D D D D D D D D W Wi   
      WiWiW                               W           W         W t t t W D D D D D D D D D W                     W                                   W D D D D D D D D D D D D D D D D W Wi
      WiWiW                   W           W           W         W t t t W D D D D D D W W W W                     W                       W           W D D D D D D D D D D D D D D D D W Wi
      WiWiW                   W           W           W         W t t t W D D D D D D T T T W                     W                       W           W D D D D D D D D D D D D D D D D W Wi
      WiWiW                   W W   W W W W W W W W W W W W W W W       W W W W W W W W W   W W W W W W W   W W W W W W W W W W   W W W W W           W D D D D D D D D D D D D D D D D W Wi
      WiWiW                   W                                                                                                           W           W D D D D D D D D D D D D D D D D W Wi
      WiWiW W W W W W W W W W W                                                                                                           W           W D D D D D D D D D D D D D D D D W Wi
      WiWiW                   W                                                                                                           L           W D D D D D D D D D D D D D D D D W Wi
      WiWiW                   W                                                                                                           L           W D D D D D D D D D D D D D D D D W Wi
      WiWiW                   W                                                                                                           W           W D D D D D D D D D D D D D D D D W Wi
      WiWiW                   W                                                                                                           W           W D D D D D D D D D D D D D D D D W Wi
      WiWiW                   W             S         S         S           W W W W W W W W W W W W W W W W   W W W W W W W W W W W W W W W           W D D D D D D D D D D D D D D D D W Wi
      WiWiW                   W                                             W                                   W                         W           W D D D D D D D D D D D D D D D D W Wi
      WiWiW                   W                                                                                 W                         W           W D D D D D D D D D D D D D D D D W Wi
      WiWiW                   W                                             W                                   W                         W           W D D D D D D D D D D D D D D D D W Wi
      WiWiW W W W W W W W W W W                                             W                                   W                         W           W D D D D D D D D D D D D D D D D W Wi
      WiWiW                   W                                             W                                   W W W W W W W W W W W W W W W W W W W W D D D D D D D D D D D D D D D D W Wi
      WiWiW                   W             W           W t t t W W W W W W W                                   W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi
      WiWiW                   W             W           W t t t W           W                                   W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi                                         
      WiWiW                   W             W           W t t t W           W                                   W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi                                         
      WiWiW                   W             W           W t t t W                                               W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi                                         
      WiWiW                   W             W           W W W W W W W W W W W W W W W W W W W W W W W W W W W W W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi                          W W W W             
      WiWiW                   W             W t t t t t W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi                          W     W        
      WiWiW                   W             W t t t t t W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi                          W     W        
      WiWiW W W W W W W W W W W             W t t t t t W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi                          W     W        
      WiWiW                   W             W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi                          W     W
      WiWiW                   W             W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi                    W W W W W W W W W W
      WiWiW                   W             W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi                    W     W     W     W
      WiWiW                   W             W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi                    W     W     W     W
      WiWiW                                 W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi                    W W W W     W W W W 
      WiWiW                   W             W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi
      WiWiW                   W             W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi
      WiWiW W W W W W W W W W W             W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi  
      WiWiW                   W             W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi 
      WiWiW                   W             W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi 
      WiWiW                   W             W D D D D D D D D D D D D D b D D D D D D D D b D D D D D D b D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi 
      WiWiW                   W             W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi 
      WiWiW                                 W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi 
      WiWiW                   W             W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi 
      WiWiW                   W             W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi 
      WiWiW W W W W W W W W W W             W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi 
      WiWiW                   W             W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi 
      WiWiW                   W             W D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D W Wi 
WiWiWiWiWiW                                 W W W W W W W W W     W W W W W W W W W W W W W W     W W W W W W W W     W W W W W W W W W W W W W     W W W W W W W W W W W               W Wi                                                                                                                                                                                                                                W
WiWiWiWiWiW                   W                           W         W         W                                                         W               W               W               W Wi               
WiW W W W W W W W W W W W W W W                           W W     W W   Ot    W                                                         W               W W W W W W W W W               W Wi               
WiW         W   ek            W t t t t t W t t t W t t t W         W   Ot    W                                                         W               W   W           W               W Wi                    
WiW         W                 W t t t t t W t t t W t t t W         W   Ot    W                                                         W               W   W           W               W Wi                
WiW         W W W W W W W   W W t t t t t W V2V2V2W t t t W         W         W         W           W           W           W           W                               W               W Wi               
WiW         W                             W W W W W       W         W W W   W W         W           W           W           W           W               W   W           W               W Wi                 
WiW         W               W             W                         W         W                                                         W               W W W W W W W W W               W Wi            
WiW         W               W             W                       E1W         W                                                         W                 WiT T T       W               W Wi            
WiW         W               W                                                                                   E1                                        WiT T T       W               W Wi            
WiW         W W W W W W W W W             W                         W         W                                                         W                 WiT T T       W               W Wi               
WiW                                       W W W W W W W W W W W W W W         W W W W W W W W W W W W           W           W           W               W W W W W W W W W               W Wi               
WiW                                       W             W           W         W                     W Ha                Ot              W               W   W           W               W Wi               
WiW                                                                           W     OtOtOt  Ot      W Hm        P       Ot              W               W   W           W               W Wi                
WiW                                       W                                   W             Ot      W Hm                Ot              W                               W               W Wi               
WiW                                       W                                         OtOtOtO         W Hm                                W               W   W           W               W Wi                
WiW                                       W       Ot    Ot      Ot            W                     W He                                W               W W W W W W W W W               W Wi
WiW                                       W                                   W                     W                                   W               W               W               W Wi
WiW W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W Wi
WiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWi
    `