var map3 = `
WiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWi
WitLtLtLtLtLtLtLtLtLtLtLtLtLtLtLtLtLWi
WitLtLtLtLtLtLtLtLtLtLtLtLtLtLtLtLtLWi
WitLtLtLtLtLtLtLtLtLtLtLtLtLtLtLtLtLWi
WitLtLtLtLtLtLtLtLtLtLtLtLtLtLtLtLtLWi
WitLtLtLtLtLtLtLtLtLtLtLtLtLtLtLtLtLWi
WitLtLtLtLtL            tLtLtLtLtLtLWi
WitLtLtLtLtL  P     V4  tLtLtLtLtLtLWi
WitLtLtLtLtL            tLtLtLtLtLtLWi
WitLtLtLtLtLtLtLtLtLtLtLtLtLtLtLtLtLWi
WitLtLtLtLtLtLtLtLtLtLtLtLtLtLtLtLtLWi
WitLtLtLtLtLtLtLtLtLtLtLtLtLtLtLtLtLWi
WitLtLtLtLtLtLtLtLtLtLtLtLtLtLtLtLtLWi
WitLtLtLtLtLtLtLtLtLtLtLtLtLtLtLtLtLWi
WiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWiWi
`
